### ISSUE TITLE
Angular 2 Redis Integration

### ISSUE THREAD

**Issue by vyakymenko** [vyakymenko/angular2-seed-express#5]
Client-Server ng2 Redis integration:
- [x] Server side service `name-list.service.ts`.
- [x] Get (`client`) `name-list`, parsed from `Redis`
- [ ] Add (`client`) `name` to `name-list`.
- [ ] Delete (`client`) `name` from `name-list`.

Create `server` service for some new test `CRUD` game/app.
- [ ] App/Game proposition.
- [ ] Server side service for `app/game`.
- [ ] Client-side logic.

**Comment by DmitryEfimenko** [comment]
I wanted to clarify the purpose of Redis in this project. Is that basically a database? The persistent storage layer? If so, the logic of accessing it should be moved out to some service like `storageService` with an appropriate interface so that people who don't want to use Redis can easily switch it out to something else.

**Comment by vyakymenko** [comment]
@DmitryEfimenko , it's will be just an example how to work with `database`.
Of course, developers can use any another way that they want. But we need to give something for them for start.

**Comment by balaguero** [comment]
I'm working on add mongodb and mongoose, and jwt.
In order to create an unser register and login component.
If i can finish it, i'll share with you :)
---
Nice Repo

PD: it's the first time that i working with ng-2 fullstack, maybe the code can contain some errors.
PD: if you can add live-reload to server will be great!

**Comment by vyakymenko** [comment]
@balaguero , thank you will look for your improvement. Actually, for now, have a lot of work, so when I will have little bit free time will implement a lot of interesting features. Thanks!
